### ISSUE TITLE
CSS-də şərh yazmaq üçün /* və */ simvollarından istifadə olunur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Ceyran199/PragmatechFoundationProject#7]
CSS-də şərh yazmaq üçün `/*` və `*/` simvollarından istifadə olunur. Siz belə `<!-- Section Start -->` yazmısınız, səhvdir. Bu simvoldan HTML-də şərh yazmaq üçün istifadə olunur.

_Məsələn:_

```html
<!-- footer start -->
<footer>
  <p>Author: Samir Karimov</p>
</footer>
```

```css
/* footer start */
footer {
  margin: 0;
  width: 100%;
}
```
